import { jsPDF } from "jspdf"
import { AnalysisReport } from "@/types"

type RGB = [number, number, number]

const COLORS: Record<string, RGB> = {
  A: [34, 197, 94],
  B: [59, 130, 246],
  C: [245, 158, 11],
  D: [239, 68, 68],
  pass: [34, 197, 94],
  fail: [239, 68, 68],
  text: [31, 41, 55],
  muted: [107, 114, 128],
  heading: [17, 24, 39],
}

function setColor(doc: jsPDF, color: RGB) {
  doc.setTextColor(color[0], color[1], color[2])
}

export function generatePdf(report: AnalysisReport): Buffer {
  const doc = new jsPDF({ unit: "mm", format: "a4" })
  const pageWidth = doc.internal.pageSize.getWidth()
  const margin = 20
  let y = 20

  function checkPageBreak(needed: number) {
    if (y + needed > 270) {
      doc.addPage()
      y = 20
    }
  }

  // Header
  doc.setFontSize(22)
  setColor(doc, COLORS.heading)
  doc.text("SEO / AEO / GEO Grader Report", margin, y)
  y += 10

  doc.setFontSize(10)
  setColor(doc, COLORS.muted)
  doc.text(`URL: ${report.url}`, margin, y)
  y += 5
  doc.text(
    `Analyzed: ${new Date(report.analyzedAt).toLocaleString()}`,
    margin,
    y
  )
  y += 10

  // Overall grade
  const gradeColor = COLORS[report.overallGrade]
  doc.setFontSize(48)
  setColor(doc, gradeColor)
  doc.text(report.overallGrade, pageWidth / 2 - 10, y + 15)
  doc.setFontSize(16)
  doc.text(`${report.overallPercentage}%`, pageWidth / 2 + 5, y + 15)
  y += 25

  doc.setFontSize(11)
  setColor(doc, COLORS.text)
  doc.text(
    `${report.overallPassed} of ${report.overallTotal} checks passed`,
    margin,
    y
  )
  y += 5

  // Grade thresholds legend
  doc.setFontSize(8)
  setColor(doc, COLORS.muted)
  doc.text(
    "A \u2265 90% | B \u2265 75% | C \u2265 58% | D < 58%",
    margin,
    y
  )
  y += 10

  // Divider
  doc.setDrawColor(229, 231, 235)
  doc.setLineWidth(0.5)
  doc.line(margin, y, pageWidth - margin, y)
  y += 8

  // Categories
  for (const cat of report.categories) {
    checkPageBreak(40)

    const catGradeColor = COLORS[cat.grade]

    doc.setFontSize(14)
    setColor(doc, COLORS.heading)
    doc.text(`${cat.category}`, margin, y)

    setColor(doc, catGradeColor)
    doc.text(
      `${cat.grade} (${cat.percentage}%)`,
      pageWidth - margin - 30,
      y
    )
    y += 7

    for (const check of cat.checks) {
      checkPageBreak(12)
      const icon = check.passed ? "\u2713" : "\u2717"
      const color = check.passed ? COLORS.pass : COLORS.fail

      doc.setFontSize(10)
      setColor(doc, color)
      doc.text(icon, margin + 2, y)

      setColor(doc, COLORS.text)
      doc.text(check.name, margin + 8, y)

      doc.setFontSize(8)
      setColor(doc, COLORS.muted)
      const detailsWidth = pageWidth - margin * 2 - 8
      const lines = doc.splitTextToSize(check.details, detailsWidth)
      doc.text(lines, margin + 8, y + 4)
      y += 5 + lines.length * 3.5
    }

    y += 5
  }

  // Rubric section
  checkPageBreak(60)
  y += 5
  doc.setDrawColor(229, 231, 235)
  doc.line(margin, y, pageWidth - margin, y)
  y += 8

  doc.setFontSize(14)
  setColor(doc, COLORS.heading)
  doc.text("Scoring Rubric", margin, y)
  y += 7

  const rubricLines = [
    "12 checks across 4 categories:",
    "",
    "SEO (4): Title tag, Meta description, robots.txt, XML Sitemap",
    "AEO (4): JSON-LD, Open Graph, Canonical URL, FAQ/Speakable Schema",
    "CTA (1): Call-to-action present",
    "GEO (3): Content depth (\u22651200 words), Links (\u22653), Clean copy",
    "",
    "Grade = (checks passed / 12) \u00D7 100%",
    "A \u2265 90% (11-12)  |  B \u2265 75% (9-10)  |  C \u2265 58% (7-8)  |  D < 58% (\u22646)",
  ]

  doc.setFontSize(9)
  setColor(doc, COLORS.text)
  for (const line of rubricLines) {
    checkPageBreak(6)
    doc.text(line, margin, y)
    y += 4.5
  }

  // Footer
  checkPageBreak(15)
  y += 10
  doc.setFontSize(8)
  setColor(doc, COLORS.muted)
  doc.text("Generated by SEO/AEO/GEO Grader", margin, y)

  return Buffer.from(doc.output("arraybuffer"))
}
